spring:
  #  servlet:
  #    multipart:
  #      max-file-size: 10MB
  #      max-request-size: 10MB

  h2:
    console:
      enabled: true

  liquibase:
    contexts: dev

  jpa:
    open-in-view: false

server:
  port: 8081
