#
# Generate the table used to store recipe data
#
databaseChangeLog:

  - changeSet:
      id: 20190809-table-recipe-create
      author: leswilson
      changes:
        - preConditions:
            - not:
                - tableExists:
                    tableName: recipe
        - createTable:
            tableName: recipe
            columns:
              - column:
                  name: id
                  type: int
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: varchar(250)
                  constraints:
                    nullable: false
              - column:
                  name: prep_time
                  type: int
              - column:
                  name: cook_time
                  type: int
              - column:
                  name: servings
                  type: int
              - column:
                  name: source
                  type: varchar(500)
              - column:
                  name: url
                  type: varchar(500)
              - column:
                  name: directions
                  type: varchar(3000)
              - column:
                  name: difficulty
                  type: varchar(30)
              - column:
                  name: image
                  type: blob
              - column:
                  name: notes_id
                  type: int
              - column:
                  name: created_at
                  type: datetime
                  defaultValueComputed: current_datetime
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: datetime
                  defaultValueComputed: current_datetime
                  constraints:
                    nullable: false

  - changeSet:
      id: 20190809-table-recipe-add-primary-key
      author: leswilson
      changes:
        - preConditions:
            - not:
                - primaryKeyExists:
                    tableName: recipe
        - addPrimaryKey:
            columnNames: id
            constraintName: pk_recipe
            tableName: recipe
